In [1]:
import pandas as pd

In [6]:
df = pd.read_csv('nba.csv')

In [7]:
pwd

'C:\\Users\\hp\\OneDrive\\CLEAR\\3.A.PANDAS'

In [8]:
df.head(3)

,Name,Team,Number,Position,Age,Height,Weight,College,Salary,Bonus,Sales
0,Avery Bradley,Boston Celtics,0.0,PG,25.0,06-Feb,180.0,Texas,7730337.0,NaN,NaN
1,Jae Crowder,Boston Celtics,99.0,SF,25.0,06-Jun,235.0,Marquette,6796117.0,NaN,NaN
2,John Holland,Boston Celtics,30.0,SG,27.0,06-May,205.0,Boston University,NaN,NaN,NaN

In [9]:
df.head(5)

,Name,Team,Number,Position,Age,Height,Weight,College,Salary,Bonus,Sales
0,Avery Bradley,Boston Celtics,0.0,PG,25.0,06-Feb,180.0,Texas,7730337.0,NaN,NaN
1,Jae Crowder,Boston Celtics,99.0,SF,25.0,06-Jun,235.0,Marquette,6796117.0,NaN,NaN
2,John Holland,Boston Celtics,30.0,SG,27.0,06-May,205.0,Boston University,NaN,NaN,NaN
3,R.J. Hunter,Boston Celtics,28.0,SG,22.0,06-May,185.0,Georgia State,1148640.0,NaN,NaN
4,Jonas Jerebko,Boston Celtics,8.0,PF,29.0,06-Oct,231.0,NaN,5000000.0,NaN,NaN

In [11]:
pd.set_option('display.max_rows',500)

In [12]:
pd.set_option('display.max_rows',None)

In [14]:
df.head(100)

,Name,Team,Number,Position,Age,Height,Weight,College,Salary,Bonus,Sales
0,Avery Bradley,Boston Celtics,0.0,PG,25.0,06-Feb,180.0,Texas,7730337.0,NaN,NaN
1,Jae Crowder,Boston Celtics,99.0,SF,25.0,06-Jun,235.0,Marquette,6796117.0,NaN,NaN
2,John Holland,Boston Celtics,30.0,SG,27.0,06-May,205.0,Boston University,NaN,NaN,NaN
3,R.J. Hunter,Boston Celtics,28.0,SG,22.0,06-May,185.0,Georgia State,1148640.0,NaN,NaN
4,Jonas Jerebko,Boston Celtics,8.0,PF,29.0,06-Oct,231.0,NaN,5000000.0,NaN,NaN
5,Amir Johnson,Boston Celtics,90.0,PF,29.0,06-Sep,240.0,NaN,12000000.0,NaN,NaN
6,Jordan Mickey,Boston Celtics,55.0,PF,21.0,06-Aug,235.0,LSU,1170960.0,NaN,NaN
7,Kelly Olynyk,Boston Celtics,41.0,C,25.0,7-0,238.0,Gonzaga,2165160.0,NaN,NaN
8,Terry Rozier,Boston Celtics,12.0,PG,22.0,06-Feb,190.0,Louisville,1824360.0,NaN,NaN
9,Marcus Smart,Boston Celtics,36.0,PG,22.0,06-Apr,220.0,Oklahoma State,3431040.0,NaN,NaN
10,Jared Sullinger,Boston Celtics,7.0,C,24.0,06-Sep,260.0,Ohio State,2569260.0,NaN,NaN
11,Isaiah Thomas,Boston Celtics,4.0,PG,27.0,05-Sep,185.0,Washington,6912869.0,NaN,NaN
12,Evan Turner,Boston Celtics,11.0,SG,27.0,06-Jul,220.0,Ohio State,3425510.0,NaN,NaN
13,James Young,Boston Celtics,13.0,SG,20.0,06-Jun,215.0,Kentucky,1749840.0,NaN,NaN
14,Tyler Zeller,Boston Celtics,44.0,C,26.0,7-0,253.0,North Carolina,2616975.0,NaN,NaN
15,Bojan Bogdanovic,Brooklyn Nets,44.0,SG,27.0,06-Aug,216.0,NaN,3425510.0,NaN,NaN
16,Markel Brown,Brooklyn Nets,22.0,SG,24.0,06-Mar,190.0,Oklahoma State,845059.0,NaN,NaN
17,Wayne Ellington,Brooklyn Nets,21.0,SG,28.0,06-Apr,200.0,North Carolina,1500000.0,NaN,NaN
18,Rondae Hollis-Jefferson,Brooklyn Nets,24.0,SG,21.0,06-Jul,220.0,Arizona,1335480.0,NaN,NaN
19,Jarrett Jack,Brooklyn Nets,2.0,PG,32.0,06-Mar,200.0,Georgia Tech,6300000.0,NaN,NaN
20,Sergey Karasev,Brooklyn Nets,10.0,SG,22.0,06-Jul,208.0,NaN,1599840.0,NaN,NaN
21,Sean Kilpatrick,Brooklyn Nets,6.0,SG,26.0,06-Apr,219.0,Cincinnati,134215.0,NaN,NaN
22,Shane Larkin,Brooklyn Nets,0.0,PG,23.0,05-Nov,175.0,Miami (FL),1500000.0,NaN,NaN
23,Brook Lopez,Brooklyn Nets,11.0,C,28.0,7-0,275.0,Stanford,19689000.0,NaN,NaN
24,Chris McCullough,Brooklyn Nets,1.0,PF,21.0,06-Nov,200.0,Syracuse,1140240.0,NaN,NaN
25,Willie Reed,Brooklyn Nets,33.0,PF,26.0,06-Oct,220.0,Saint Louis,947276.0,NaN,NaN
26,Thomas Robinson,Brooklyn Nets,41.0,PF,25.0,06-Oct,237.0,Kansas,981348.0,NaN,NaN
27,Henry Sims,Brooklyn Nets,14.0,C,26.0,06-Oct,248.0,Georgetown,947276.0,NaN,NaN
28,Donald Sloan,Brooklyn Nets,15.0,PG,28.0,06-Mar,205.0,Texas A&M,947276.0,NaN,NaN
29,Thaddeus Young,Brooklyn Nets,30.0,PF,27.0,06-Aug,221.0,Georgia Tech,11235955.0,NaN,NaN
30,Arron Afflalo,New York Knicks,4.0,SG,30.0,06-May,210.0,UCLA,8000000.0,NaN,NaN
31,Lou Amundson,New York Knicks,17.0,PF,33.0,06-Sep,220.0,UNLV,1635476.0,NaN,NaN
32,Thanasis Antetokounmpo,New York Knicks,43.0,SF,23.0,06-Jul,205.0,NaN,30888.0,NaN,NaN
33,Carmelo Anthony,New York Knicks,7.0,SF,32.0,06-Aug,240.0,Syracuse,22875000.0,NaN,NaN
34,Jose Calderon,New York Knicks,3.0,PG,34.0,06-Mar,200.0,NaN,7402812.0,NaN,NaN
35,Cleanthony Early,New York Knicks,11.0,SF,25.0,06-Aug,210.0,Wichita State,845059.0,NaN,NaN
36,Langston Galloway,New York Knicks,2.0,SG,24.0,06-Feb,200.0,Saint Joseph's,845059.0,NaN,NaN
37,Jerian Grant,New York Knicks,13.0,PG,23.0,06-Apr,195.0,Notre Dame,1572360.0,NaN,NaN
38,Robin Lopez,New York Knicks,8.0,C,28.0,7-0,255.0,Stanford,12650000.0,NaN,NaN
39,Kyle O'Quinn,New York Knicks,9.0,PF,26.0,06-Oct,250.0,Norfolk State,3750000.0,NaN,NaN
40,Kristaps Porzingis,New York Knicks,6.0,PF,20.0,07-Mar,240.0,NaN,4131720.0,NaN,NaN
41,Kevin Seraphin,New York Knicks,1.0,C,26.0,06-Oct,278.0,NaN,2814000.0,NaN,NaN
42,Lance Thomas,New York Knicks,42.0,SF,28.0,06-Aug,235.0,Duke,1636842.0,NaN,NaN
43,Sasha Vujacic,New York Knicks,18.0,SG,32.0,06-Jul,195.0,NaN,947276.0,NaN,NaN
44,Derrick Williams,New York Knicks,23.0,PF,25.0,06-Aug,240.0,Arizona,4000000.0,NaN,NaN
45,Tony Wroten,New York Knicks,5.0,SG,23.0,06-Jun,205.0,Washington,167406.0,NaN,NaN
46,Elton Brand,Philadelphia 76ers,42.0,PF,37.0,06-Sep,254.0,Duke,NaN,NaN,NaN
47,Isaiah Canaan,Philadelphia 76ers,0.0,PG,25.0,6-0,201.0,Murray State,947276.0,NaN,NaN
48,Robert Covington,Philadelphia 76ers,33.0,SF,25.0,06-Sep,215.0,Tennessee State,1000000.0,NaN,NaN
49,Joel Embiid,Philadelphia 76ers,21.0,C,22.0,7-0,250.0,Kansas,4626960.0,NaN,NaN
50,Jerami Grant,Philadelphia 76ers,39.0,SF,22.0,06-Aug,210.0,Syracuse,845059.0,NaN,NaN
51,Richaun Holmes,Philadelphia 76ers,22.0,PF,22.0,06-Oct,245.0,Bowling Green,1074169.0,NaN,NaN
52,Carl Landry,Philadelphia 76ers,7.0,PF,32.0,06-Sep,248.0,Purdue,6500000.0,NaN,NaN
53,Kendall Marshall,Philadelphia 76ers,5.0,PG,24.0,06-Apr,200.0,North Carolina,2144772.0,NaN,NaN
54,T.J. McConnell,Philadelphia 76ers,12.0,PG,24.0,06-Feb,200.0,Arizona,525093.0,NaN,NaN
55,Nerlens Noel,Philadelphia 76ers,4.0,PF,22.0,06-Nov,228.0,Kentucky,3457800.0,NaN,NaN
56,Jahlil Okafor,Philadelphia 76ers,8.0,C,20.0,06-Nov,275.0,Duke,4582680.0,NaN,NaN
57,Ish Smith,Philadelphia 76ers,1.0,PG,27.0,6-0,175.0,Wake Forest,947276.0,NaN,NaN
58,Nik Stauskas,Philadelphia 76ers,11.0,SG,22.0,06-Jun,205.0,Michigan,2869440.0,NaN,NaN
59,Hollis Thompson,Philadelphia 76ers,31.0,SG,25.0,06-Aug,206.0,Georgetown,947276.0,NaN,NaN
60,Christian Wood,Philadelphia 76ers,35.0,PF,20.0,06-Nov,220.0,UNLV,525093.0,NaN,NaN
61,Bismack Biyombo,Toronto Raptors,8.0,C,23.0,06-Sep,245.0,NaN,2814000.0,NaN,NaN
62,Bruno Caboclo,Toronto Raptors,20.0,SF,20.0,06-Sep,205.0,NaN,1524000.0,NaN,NaN
63,DeMarre Carroll,Toronto Raptors,5.0,SF,29.0,06-Aug,212.0,Missouri,13600000.0,NaN,NaN
64,DeMar DeRozan,Toronto Raptors,10.0,SG,26.0,06-Jul,220.0,USC,10050000.0,NaN,NaN
65,James Johnson,Toronto Raptors,3.0,PF,29.0,06-Sep,250.0,Wake Forest,2500000.0,NaN,NaN
66,Cory Joseph,Toronto Raptors,6.0,PG,24.0,06-Mar,190.0,Texas,7000000.0,NaN,NaN
67,Kyle Lowry,Toronto Raptors,7.0,PG,30.0,6-0,205.0,Villanova,12000000.0,NaN,NaN
68,Lucas Nogueira,Toronto Raptors,92.0,C,23.0,7-0,220.0,NaN,1842000.0,NaN,NaN
69,Patrick Patterson,Toronto Raptors,54.0,PF,27.0,06-Sep,235.0,Kentucky,6268675.0,NaN,NaN
70,Norman Powell,Toronto Raptors,24.0,SG,23.0,06-Apr,215.0,UCLA,650000.0,NaN,NaN
71,Terrence Ross,Toronto Raptors,31.0,SF,25.0,06-Jul,195.0,Washington,3553917.0,NaN,NaN
72,Luis Scola,Toronto Raptors,4.0,PF,36.0,06-Sep,240.0,NaN,2900000.0,NaN,NaN
73,Jason Thompson,Toronto Raptors,1.0,PF,29.0,06-Nov,250.0,Rider,245177.0,NaN,NaN
74,Jonas Valanciunas,Toronto Raptors,17.0,C,24.0,7-0,255.0,NaN,4660482.0,NaN,NaN
75,Delon Wright,Toronto Raptors,55.0,PG,24.0,06-May,190.0,Utah,1509360.0,NaN,NaN
76,Leandro Barbosa,Golden State Warriors,19.0,SG,33.0,06-Mar,194.0,NaN,2500000.0,NaN,NaN
77,Harrison Barnes,Golden State Warriors,40.0,SF,24.0,06-Aug,225.0,North Carolina,3873398.0,NaN,NaN
78,Andrew Bogut,Golden State Warriors,12.0,C,31.0,7-0,260.0,Utah,13800000.0,NaN,NaN
79,Ian Clark,Golden State Warriors,21.0,SG,25.0,06-Mar,175.0,Belmont,947276.0,NaN,NaN
80,Stephen Curry,Golden State Warriors,30.0,PG,28.0,06-Mar,190.0,Davidson,11370786.0,NaN,NaN
81,Festus Ezeli,Golden State Warriors,31.0,C,26.0,06-Nov,265.0,Vanderbilt,2008748.0,NaN,NaN
82,Draymond Green,Golden State Warriors,23.0,PF,26.0,06-Jul,230.0,Michigan State,14260870.0,NaN,NaN
83,Andre Iguodala,Golden State Warriors,9.0,SF,32.0,06-Jun,215.0,Arizona,11710456.0,NaN,NaN
84,Shaun Livingston,Golden State Warriors,34.0,PG,30.0,06-Jul,192.0,NaN,5543725.0,NaN,NaN
85,Kevon Looney,Golden State Warriors,36.0,SF,20.0,06-Sep,220.0,UCLA,1131960.0,NaN,NaN
86,James Michael McAdoo,Golden State Warriors,20.0,SF,23.0,06-Sep,240.0,North Carolina,845059.0,NaN,NaN
87,Brandon Rush,Golden State Warriors,4.0,SF,30.0,06-Jun,220.0,Kansas,1270964.0,NaN,NaN
88,Marreese Speights,Golden State Warriors,5.0,C,28.0,06-Oct,255.0,Florida,3815000.0,NaN,NaN
89,Klay Thompson,Golden State Warriors,11.0,SG,26.0,06-Jul,215.0,Washington State,15501000.0,NaN,NaN
90,Anderson Varejao,Golden State Warriors,18.0,PF,33.0,06-Nov,273.0,NaN,289755.0,NaN,NaN
91,Cole Aldrich,Los Angeles Clippers,45.0,C,27.0,06-Nov,250.0,Kansas,1100602.0,NaN,NaN
92,Jeff Ayres,Los Angeles Clippers,19.0,PF,29.0,06-Sep,250.0,Arizona State,111444.0,NaN,NaN
93,Jamal Crawford,Los Angeles Clippers,11.0,SG,36.0,06-May,195.0,Michigan,5675000.0,NaN,NaN
94,Branden Dawson,Los Angeles Clippers,22.0,SF,23.0,06-Jun,225.0,Michigan State,525093.0,NaN,NaN
95,Jeff Green,Los Angeles Clippers,8.0,SF,29.0,06-Sep,235.0,Georgetown,9650000.0,NaN,NaN
96,Blake Griffin,Los Angeles Clippers,32.0,PF,27.0,06-Oct,251.0,Oklahoma,18907726.0,NaN,NaN
97,Wesley Johnson,Los Angeles Clippers,33.0,SF,28.0,06-Jul,215.0,Syracuse,1100602.0,NaN,NaN
98,DeAndre Jordan,Los Angeles Clippers,6.0,C,27.0,06-Nov,265.0,Texas A&M,19689000.0,NaN,NaN
99,Luc Richard Mbah a Moute,Los Angeles Clippers,12.0,PF,29.0,06-Aug,230.0,UCLA,947276.0,NaN,NaN

In [17]:
pd.set_option('display.max_columns',30)

In [18]:
df.head(3)

,Name,Team,Number,Position,Age,Height,Weight,College,Salary,Bonus,Sales
0,Avery Bradley,Boston Celtics,0.0,PG,25.0,06-Feb,180.0,Texas,7730337.0,NaN,NaN
1,Jae Crowder,Boston Celtics,99.0,SF,25.0,06-Jun,235.0,Marquette,6796117.0,NaN,NaN
2,John Holland,Boston Celtics,30.0,SG,27.0,06-May,205.0,Boston University,NaN,NaN,NaN

In [19]:
df.tail(30)

,Name,Team,Number,Position,Age,Height,Weight,College,Salary,Bonus,Sales
427,Cliff Alexander,Portland Trail Blazers,34.0,PF,20.0,06-Aug,240.0,Kansas,525093.0,NaN,NaN
428,Al-Farouq Aminu,Portland Trail Blazers,8.0,SF,25.0,06-Sep,215.0,Wake Forest,8042895.0,NaN,NaN
429,Pat Connaughton,Portland Trail Blazers,5.0,SG,23.0,06-May,206.0,Notre Dame,625093.0,NaN,NaN
430,Allen Crabbe,Portland Trail Blazers,23.0,SG,24.0,06-Jun,210.0,California,947276.0,NaN,NaN
431,Ed Davis,Portland Trail Blazers,17.0,C,27.0,06-Oct,240.0,North Carolina,6980802.0,NaN,NaN
432,Maurice Harkless,Portland Trail Blazers,4.0,SF,23.0,06-Sep,215.0,St. John's,2894059.0,NaN,NaN
433,Gerald Henderson,Portland Trail Blazers,9.0,SG,28.0,06-May,215.0,Duke,6000000.0,NaN,NaN
434,Chris Kaman,Portland Trail Blazers,35.0,C,34.0,7-0,265.0,Central Michigan,5016000.0,NaN,NaN
435,Meyers Leonard,Portland Trail Blazers,11.0,PF,24.0,07-Jan,245.0,Illinois,3075880.0,NaN,NaN
436,Damian Lillard,Portland Trail Blazers,0.0,PG,25.0,06-Mar,195.0,Weber State,4236287.0,NaN,NaN
437,C.J. McCollum,Portland Trail Blazers,3.0,SG,24.0,06-Apr,200.0,Lehigh,2525160.0,NaN,NaN
438,Luis Montero,Portland Trail Blazers,44.0,SG,23.0,06-Jul,185.0,Westchester CC,525093.0,NaN,NaN
439,Mason Plumlee,Portland Trail Blazers,24.0,C,26.0,06-Nov,235.0,Duke,1415520.0,NaN,NaN
440,Brian Roberts,Portland Trail Blazers,2.0,PG,30.0,06-Jan,173.0,Dayton,2854940.0,NaN,NaN
441,Noah Vonleh,Portland Trail Blazers,21.0,PF,20.0,06-Sep,240.0,Indiana,2637720.0,NaN,NaN
442,Trevor Booker,Utah Jazz,33.0,PF,28.0,06-Aug,228.0,Clemson,4775000.0,NaN,NaN
443,Trey Burke,Utah Jazz,3.0,PG,23.0,06-Jan,191.0,Michigan,2658240.0,NaN,NaN
444,Alec Burks,Utah Jazz,10.0,SG,24.0,06-Jun,214.0,Colorado,9463484.0,NaN,NaN
445,Dante Exum,Utah Jazz,11.0,PG,20.0,06-Jun,190.0,NaN,3777720.0,NaN,NaN
446,Derrick Favors,Utah Jazz,15.0,PF,24.0,06-Oct,265.0,Georgia Tech,12000000.0,NaN,NaN
447,Rudy Gobert,Utah Jazz,27.0,C,23.0,07-Jan,245.0,NaN,1175880.0,NaN,NaN
448,Gordon Hayward,Utah Jazz,20.0,SF,26.0,06-Aug,226.0,Butler,15409570.0,NaN,NaN
449,Rodney Hood,Utah Jazz,5.0,SG,23.0,06-Aug,206.0,Duke,1348440.0,NaN,NaN
450,Joe Ingles,Utah Jazz,2.0,SF,28.0,06-Aug,226.0,NaN,2050000.0,NaN,NaN
451,Chris Johnson,Utah Jazz,23.0,SF,26.0,06-Jun,206.0,Dayton,981348.0,NaN,NaN
452,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
453,Shelvin Mack,Utah Jazz,8.0,PG,26.0,06-Mar,203.0,Butler,2433333.0,NaN,NaN
454,Raul Neto,Utah Jazz,25.0,PG,24.0,06-Jan,179.0,NaN,900000.0,NaN,NaN
455,Tibor Pleiss,Utah Jazz,21.0,C,26.0,07-Mar,256.0,NaN,2900000.0,NaN,NaN
456,Jeff Withey,Utah Jazz,24.0,C,26.0,7-0,231.0,Kansas,947276.0,NaN,NaN

In [20]:
df.tail(10)

,Name,Team,Number,Position,Age,Height,Weight,College,Salary,Bonus,Sales
447,Rudy Gobert,Utah Jazz,27.0,C,23.0,07-Jan,245.0,NaN,1175880.0,NaN,NaN
448,Gordon Hayward,Utah Jazz,20.0,SF,26.0,06-Aug,226.0,Butler,15409570.0,NaN,NaN
449,Rodney Hood,Utah Jazz,5.0,SG,23.0,06-Aug,206.0,Duke,1348440.0,NaN,NaN
450,Joe Ingles,Utah Jazz,2.0,SF,28.0,06-Aug,226.0,NaN,2050000.0,NaN,NaN
451,Chris Johnson,Utah Jazz,23.0,SF,26.0,06-Jun,206.0,Dayton,981348.0,NaN,NaN
452,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
453,Shelvin Mack,Utah Jazz,8.0,PG,26.0,06-Mar,203.0,Butler,2433333.0,NaN,NaN
454,Raul Neto,Utah Jazz,25.0,PG,24.0,06-Jan,179.0,NaN,900000.0,NaN,NaN
455,Tibor Pleiss,Utah Jazz,21.0,C,26.0,07-Mar,256.0,NaN,2900000.0,NaN,NaN
456,Jeff Withey,Utah Jazz,24.0,C,26.0,7-0,231.0,Kansas,947276.0,NaN,NaN

In [21]:
df.head(3)

,Name,Team,Number,Position,Age,Height,Weight,College,Salary,Bonus,Sales
0,Avery Bradley,Boston Celtics,0.0,PG,25.0,06-Feb,180.0,Texas,7730337.0,NaN,NaN
1,Jae Crowder,Boston Celtics,99.0,SF,25.0,06-Jun,235.0,Marquette,6796117.0,NaN,NaN
2,John Holland,Boston Celtics,30.0,SG,27.0,06-May,205.0,Boston University,NaN,NaN,NaN

In [23]:
df.tail(3)

,Name,Team,Number,Position,Age,Height,Weight,College,Salary,Bonus,Sales
454,Raul Neto,Utah Jazz,25.0,PG,24.0,06-Jan,179.0,NaN,900000.0,NaN,NaN
455,Tibor Pleiss,Utah Jazz,21.0,C,26.0,07-Mar,256.0,NaN,2900000.0,NaN,NaN
456,Jeff Withey,Utah Jazz,24.0,C,26.0,7-0,231.0,Kansas,947276.0,NaN,NaN

In [24]:
df.ndim

2

In [25]:
df.shape

(457, 11)

In [26]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 457 entries, 0 to 456
Data columns (total 11 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Name      456 non-null    object
 1   Team      456 non-null    object
 2   Number    456 non-null    float64
 3   Position  456 non-null    object
 4   Age       456 non-null    float64
 5   Height    456 non-null    object
 6   Weight    456 non-null    float64
 7   College   372 non-null    object
 8   Salary    445 non-null    float64
 9   Bonus     0 non-null      float64
 10  Sales     0 non-null      float64
dtypes: float64(6), object(5)
memory usage: 39.4+ KB

In [27]:
df.isnull().sum()

Name          1
Team          1
Number        1
Position      1
Age           1
Height        1
Weight        1
College      85
Salary       12
Bonus       457
Sales       457
dtype: int64

In [28]:
df.columns

Index(['Name', 'Team', 'Number', 'Position', 'Age', 'Height', 'Weight',
       'College', 'Salary', 'Bonus', 'Sales'],
      dtype='object')

In [29]:
df[['Age']]

      Age
0    25.0
1    25.0
2    27.0
3    22.0
4    29.0
5    29.0
6    21.0
7    25.0
8    22.0
9    22.0
10   24.0
11   27.0
12   27.0
13   20.0
14   26.0
15   27.0
16   24.0
17   28.0
18   21.0
19   32.0
20   22.0
21   26.0
22   23.0
23   28.0
24   21.0
25   26.0
26   25.0
27   26.0
28   28.0
29   27.0
30   30.0
31   33.0
32   23.0
33   32.0
34   34.0
35   25.0
36   24.0
37   23.0
38   28.0
39   26.0
40   20.0
41   26.0
42   28.0
43   32.0
44   25.0
45   23.0
46   37.0
47   25.0
48   25.0
49   22.0
50   22.0
51   22.0
52   32.0
53   24.0
54   24.0
55   22.0
56   20.0
57   27.0
58   22.0
59   25.0
60   20.0
61   23.0
62   20.0
63   29.0
64   26.0
65   29.0
66   24.0
67   30.0
68   23.0
69   27.0
70   23.0
71   25.0
72   36.0
73   29.0
74   24.0
75   24.0
76   33.0
77   24.0
78   31.0
79   25.0
80   28.0
81   26.0
82   26.0
83   32.0
84   30.0
85   20.0
86   23.0
87   30.0
88   28.0
89   26.0
90   33.0
91   27.0
92   29.0
93   36.0
94   23.0
95   29.0
96   27.0
97   28.0
98   27.0
99   29.0
100  31.0
101  38.0
102  39.0
103  31.0
104  23.0
105  25.0
106  31.0
107  24.0
108  23.0
109  37.0
110  24.0
111  29.0
112  33.0
113  25.0
114  23.0
115  21.0
116  20.0
117  27.0
118  29.0
119  36.0
120  31.0
121  26.0
122  19.0
123  28.0
124  33.0
125  21.0
126  25.0
127  24.0
128  22.0
129  27.0
130  25.0
131  32.0
132  30.0
133  31.0
134  22.0
135  23.0
136  25.0
137  27.0
138  30.0
139  36.0
140  27.0
141  22.0
142  28.0
143  25.0
144  25.0
145  24.0
146  29.0
147  27.0
148  23.0
149  24.0
150  30.0
151  25.0
152  31.0
153  26.0
154  35.0
155  23.0
156  35.0
157  30.0
158  27.0
159  24.0
160  25.0
161  27.0
162  31.0
163  21.0
164  27.0
165  24.0
166  25.0
167  33.0
168  24.0
169  31.0
170  35.0
171  35.0
172  35.0
173  31.0
174  27.0
175  25.0
176  29.0
177  25.0
178  30.0
179  25.0
180  33.0
181  33.0
182  29.0
183  36.0
184  25.0
185  25.0
186  23.0
187  23.0
188  22.0
189  23.0
190  23.0
191  26.0
192  20.0
193  28.0
194  26.0
195  31.0
196  27.0
197  24.0
198  30.0
199  26.0
200  30.0
201  28.0
202  25.0
203  28.0
204  29.0
205  29.0
206  22.0
207  30.0
208  20.0
209  25.0
210  23.0
211  21.0
212  27.0
213  24.0
214  25.0
215  21.0
216  25.0
217  21.0
218  28.0
219  24.0
220  26.0
221  32.0
222  23.0
223  21.0
224  27.0
225  29.0
226  19.0
227  22.0
228  31.0
229  28.0
230  31.0
231  33.0
232  33.0
233  29.0
234  28.0
235  29.0
236  37.0
237  32.0
238  27.0
239  24.0
240  31.0
241  31.0
242  30.0
243  27.0
244  27.0
245  30.0
246  22.0
247  22.0
248  27.0
249  26.0
250  22.0
251  30.0
252  24.0
253  23.0
254  25.0
255  30.0
256  38.0
257  21.0
258  34.0
259  37.0
260  36.0
261  39.0
262  28.0
263  23.0
264  29.0
265  31.0
266  25.0
267  23.0
268  22.0
269  24.0
270  24.0
271  34.0
272  25.0
273  28.0
274  28.0
275  28.0
276  28.0
277  29.0
278  26.0
279  27.0
280  29.0
281  23.0
282  23.0
283  30.0
284  25.0
285  26.0
286  25.0
287  29.0
288  27.0
289  25.0
290  25.0
291  27.0
292  31.0
293  28.0
294  30.0
295  22.0
296  36.0
297  34.0
298  40.0
299  38.0
300  28.0
301  24.0
302  27.0
303  33.0
304  40.0
305  27.0
306  34.0
307  26.0
308  35.0
309  26.0
310  24.0
311  35.0
312  30.0
313  31.0
314  35.0
315  31.0
316  24.0
317  24.0
318  22.0
319  27.0
320  32.0
321  31.0
322  24.0
323  27.0
324  27.0
325  24.0
326  27.0
327  30.0
328  21.0
329  28.0
330  31.0
331  23.0
332  22.0
333  24.0
334  30.0
335  27.0
336  26.0
337  29.0
338  23.0
339  32.0
340  31.0
341  30.0
342  30.0
343  36.0
344  34.0
345  24.0
346  29.0
347  22.0
348  33.0
349  34.0
350  23.0
351  26.0
352  20.0
353  30.0
354  26.0
355  23.0
356  20.0
357  21.0
358  29.0
359  26.0
360  23.0
361  24.0
362  26.0
363  24.0
364  22.0
365  30.0
366  25.0
367  32.0
368  33.0
369  22.0
370  30.0
371  24.0
372  34.0
373  32.0
374  27.0
375  33.0
376  26.0
377  20.0
378  23.0
379  30.0
380  30.0
381  29.0
382  25.0
383  28.0
384  28.0
385  25.0
386  29.0
387  26.0
388  27.0
389  21.0
390  21.0
391  24.0
392  36.0
393  20.0
394  34.0
395  21.0
396  23.0
397  23.0
398  28.0
399  26.0
400  40.0
401  20.0
402  21.0
403  23.0
404  25.0
405  30.0
406  36.0
407  25.0
408  29.0
409  25.0
410  20.0
411  21.0
412  22.0
413  35.0
414  27.0
415  32.0
416  24.0
417  26.0
418  24.0
419  24.0
420  38.0
421  30.0
422  21.0
423  24.0
424  28.0
425  24.0
426  27.0
427  20.0
428  25.0
429  23.0
430  24.0
431  27.0
432  23.0
433  28.0
434  34.0
435  24.0
436  25.0
437  24.0
438  23.0
439  26.0
440  30.0
441  20.0
442  28.0
443  23.0
444  24.0
445  20.0
446  24.0
447  23.0
448  26.0
449  23.0
450  28.0
451  26.0
452   NaN
453  26.0
454  24.0
455  26.0
456  26.0

In [31]:
newdf = df[['Team', 'Number']]

In [32]:
newdf.shape

(457, 2)

In [33]:
df.isnull().sum()

Name          1
Team          1
Number        1
Position      1
Age           1
Height        1
Weight        1
College      85
Salary       12
Bonus       457
Sales       457
dtype: int64

In [34]:
df['Age'].isnull().sum()

1

In [35]:
df = pd.read_csv('nba.csv')

In [36]:
df.head(3)

,Name,Team,Number,Position,Age,Height,Weight,College,Salary,Bonus,Sales
0,Avery Bradley,Boston Celtics,0.0,PG,25.0,06-Feb,180.0,Texas,7730337.0,NaN,NaN
1,Jae Crowder,Boston Celtics,99.0,SF,25.0,06-Jun,235.0,Marquette,6796117.0,NaN,NaN
2,John Holland,Boston Celtics,30.0,SG,27.0,06-May,205.0,Boston University,NaN,NaN,NaN

In [38]:
df = df[['Name','Age']]

In [39]:
df

                         Name   Age
0               Avery Bradley  25.0
1                 Jae Crowder  25.0
2                John Holland  27.0
3                 R.J. Hunter  22.0
4               Jonas Jerebko  29.0
5                Amir Johnson  29.0
6               Jordan Mickey  21.0
7                Kelly Olynyk  25.0
8                Terry Rozier  22.0
9                Marcus Smart  22.0
10            Jared Sullinger  24.0
11              Isaiah Thomas  27.0
12                Evan Turner  27.0
13                James Young  20.0
14               Tyler Zeller  26.0
15           Bojan Bogdanovic  27.0
16               Markel Brown  24.0
17            Wayne Ellington  28.0
18    Rondae Hollis-Jefferson  21.0
19               Jarrett Jack  32.0
20             Sergey Karasev  22.0
21            Sean Kilpatrick  26.0
22               Shane Larkin  23.0
23                Brook Lopez  28.0
24           Chris McCullough  21.0
25                Willie Reed  26.0
26            Thomas Robinson  25.0
27                 Henry Sims  26.0
28               Donald Sloan  28.0
29             Thaddeus Young  27.0
30              Arron Afflalo  30.0
31               Lou Amundson  33.0
32     Thanasis Antetokounmpo  23.0
33            Carmelo Anthony  32.0
34              Jose Calderon  34.0
35           Cleanthony Early  25.0
36          Langston Galloway  24.0
37               Jerian Grant  23.0
38                Robin Lopez  28.0
39               Kyle O'Quinn  26.0
40         Kristaps Porzingis  20.0
41             Kevin Seraphin  26.0
42               Lance Thomas  28.0
43              Sasha Vujacic  32.0
44           Derrick Williams  25.0
45                Tony Wroten  23.0
46                Elton Brand  37.0
47              Isaiah Canaan  25.0
48           Robert Covington  25.0
49                Joel Embiid  22.0
50               Jerami Grant  22.0
51             Richaun Holmes  22.0
52                Carl Landry  32.0
53           Kendall Marshall  24.0
54             T.J. McConnell  24.0
55               Nerlens Noel  22.0
56              Jahlil Okafor  20.0
57                  Ish Smith  27.0
58               Nik Stauskas  22.0
59            Hollis Thompson  25.0
60             Christian Wood  20.0
61            Bismack Biyombo  23.0
62              Bruno Caboclo  20.0
63            DeMarre Carroll  29.0
64              DeMar DeRozan  26.0
65              James Johnson  29.0
66                Cory Joseph  24.0
67                 Kyle Lowry  30.0
68             Lucas Nogueira  23.0
69          Patrick Patterson  27.0
70              Norman Powell  23.0
71              Terrence Ross  25.0
72                 Luis Scola  36.0
73             Jason Thompson  29.0
74          Jonas Valanciunas  24.0
75               Delon Wright  24.0
76            Leandro Barbosa  33.0
77            Harrison Barnes  24.0
78               Andrew Bogut  31.0
79                  Ian Clark  25.0
80              Stephen Curry  28.0
81               Festus Ezeli  26.0
82             Draymond Green  26.0
83             Andre Iguodala  32.0
84           Shaun Livingston  30.0
85               Kevon Looney  20.0
86       James Michael McAdoo  23.0
87               Brandon Rush  30.0
88          Marreese Speights  28.0
89              Klay Thompson  26.0
90           Anderson Varejao  33.0
91               Cole Aldrich  27.0
92                 Jeff Ayres  29.0
93             Jamal Crawford  36.0
94             Branden Dawson  23.0
95                 Jeff Green  29.0
96              Blake Griffin  27.0
97             Wesley Johnson  28.0
98             DeAndre Jordan  27.0
99   Luc Richard Mbah a Moute  29.0
100                Chris Paul  31.0
101               Paul Pierce  38.0
102            Pablo Prigioni  39.0
103                 JJ Redick  31.0
104             Austin Rivers  23.0
105               C.J. Wilcox  25.0
106              Brandon Bass  31.0
107               Tarik Black  24.0
108             Anthony Brown  23.0
109               Kobe Bryant  37.0
110           Jordan Clarkson  24.0
111               Roy Hibbert  29.0
112           Marcelo Huertas  33.0
113                Ryan Kelly  25.0
114           Larry Nance Jr.  23.0
115             Julius Randle  21.0
116          D'Angelo Russell  20.0
117              Robert Sacre  27.0
118            Louis Williams  29.0
119         Metta World Peace  36.0
120                Nick Young  31.0
121              Eric Bledsoe  26.0
122              Devin Booker  19.0
123            Chase Budinger  28.0
124            Tyson Chandler  33.0
125            Archie Goodwin  21.0
126              John Jenkins  25.0
127            Brandon Knight  24.0
128                  Alex Len  22.0
129                 Jon Leuer  27.0
130              Phil Pressey  25.0
131              Ronnie Price  32.0
132           Mirza Teletovic  30.0
133               P.J. Tucker  31.0
134               T.J. Warren  22.0
135             Alan Williams  23.0
136                Quincy Acy  25.0
137            James Anderson  27.0
138           Marco Belinelli  30.0
139              Caron Butler  36.0
140               Omri Casspi  27.0
141       Willie Cauley-Stein  22.0
142           Darren Collison  28.0
143          DeMarcus Cousins  25.0
144                Seth Curry  25.0
145                Duje Dukan  24.0
146                  Rudy Gay  29.0
147              Kosta Koufos  27.0
148              Ben McLemore  23.0
149             Eric Moreland  24.0
150               Rajon Rondo  30.0
151          Cameron Bairstow  25.0
152              Aaron Brooks  31.0
153              Jimmy Butler  26.0
154             Mike Dunleavy  35.0
155         Cristiano Felicio  23.0
156                 Pau Gasol  35.0
157                Taj Gibson  30.0
158            Justin Holiday  27.0
159            Doug McDermott  24.0
160            Nikola Mirotic  25.0
161             E'Twaun Moore  27.0
162               Joakim Noah  31.0
163              Bobby Portis  21.0
164              Derrick Rose  27.0
165                Tony Snell  24.0
166       Matthew Dellavedova  25.0
167             Channing Frye  33.0
168              Kyrie Irving  24.0
169              LeBron James  31.0
170         Richard Jefferson  35.0
171             Dahntay Jones  35.0
172               James Jones  35.0
173                Sasha Kaun  31.0
174                Kevin Love  27.0
175              Jordan McRae  25.0
176            Timofey Mozgov  29.0
177             Iman Shumpert  25.0
178                J.R. Smith  30.0
179          Tristan Thompson  25.0
180               Mo Williams  33.0
181              Joel Anthony  33.0
182               Aron Baynes  29.0
183               Steve Blake  36.0
184             Lorenzo Brown  25.0
185            Reggie Bullock  25.0
186  Kentavious Caldwell-Pope  23.0
187         Spencer Dinwiddie  23.0
188            Andre Drummond  22.0
189             Tobias Harris  23.0
190           Darrun Hilliard  23.0
191            Reggie Jackson  26.0
192           Stanley Johnson  20.0
193               Jodie Meeks  28.0
194             Marcus Morris  26.0
195          Anthony Tolliver  31.0
196               Lavoy Allen  27.0
197          Rakeem Christmas  24.0
198               Monta Ellis  30.0
199               Paul George  26.0
200               George Hill  30.0
201               Jordan Hill  28.0
202              Solomon Hill  25.0
203                 Ty Lawson  28.0
204               Ian Mahinmi  29.0
205                C.J. Miles  29.0
206        Glenn Robinson III  22.0
207            Rodney Stuckey  30.0
208              Myles Turner  20.0
209        Shayne Whittington  25.0
210                 Joe Young  23.0
211     Giannis Antetokounmpo  21.0
212            Jerryd Bayless  27.0
213   Michael Carter-Williams  24.0
214          Jared Cunningham  25.0
215               Tyler Ennis  21.0
216               John Henson  25.0
217             Damien Inglis  21.0
218                 O.J. Mayo  28.0
219           Khris Middleton  24.0
220               Greg Monroe  26.0
221               Steve Novak  32.0
222       Johnny O'Bryant III  23.0
223             Jabari Parker  21.0
224             Miles Plumlee  27.0
225           Greivis Vasquez  29.0
226             Rashad Vaughn  19.0
227           Justin Anderson  22.0
228                J.J. Barea  31.0
229              Jeremy Evans  28.0
230            Raymond Felton  31.0
231              Devin Harris  33.0
232                 David Lee  33.0
233           Wesley Matthews  29.0
234              JaVale McGee  28.0
235               Salah Mejri  29.0
236             Dirk Nowitzki  37.0
237             Zaza Pachulia  32.0
238          Chandler Parsons  27.0
239             Dwight Powell  24.0
240        Charlie Villanueva  31.0
241            Deron Williams  31.0
242              Trevor Ariza  30.0
243           Michael Beasley  27.0
244          Patrick Beverley  27.0
245              Corey Brewer  30.0
246              Clint Capela  22.0
247                Sam Dekker  22.0
248          Andrew Goudelock  27.0
249              James Harden  26.0
250          Montrezl Harrell  22.0
251             Dwight Howard  30.0
252            Terrence Jones  24.0
253            K.J. McDaniels  23.0
254        Donatas Motiejunas  25.0
255                Josh Smith  30.0
256               Jason Terry  38.0
257              Jordan Adams  21.0
258                Tony Allen  34.0
259            Chris Andersen  37.0
260               Matt Barnes  36.0
261              Vince Carter  39.0
262               Mike Conley  28.0
263              Bryce Cotton  23.0
264             Jordan Farmar  29.0
265                Marc Gasol  31.0
266            JaMychal Green  25.0
267             P.J. Hairston  23.0
268             Jarell Martin  22.0
269              Ray McCallum  24.0
270            Xavier Munford  24.0
271             Zach Randolph  34.0
272          Lance Stephenson  25.0
273            Alex Stepheson  28.0
274            Brandan Wright  28.0
275             Alexis Ajinca  28.0
276             Ryan Anderson  28.0
277                 Omer Asik  29.0
278              Luke Babbitt  26.0
279               Norris Cole  27.0
280          Dante Cunningham  29.0
281             Anthony Davis  23.0
282        Bryce Dejean-Jones  23.0
283             Toney Douglas  30.0
284               James Ennis  25.0
285              Tyreke Evans  26.0
286               Tim Frazier  25.0
287                Alonzo Gee  29.0
288               Eric Gordon  27.0
289           Jordan Hamilton  25.0
290              Jrue Holiday  25.0
291           Orlando Johnson  27.0
292          Kendrick Perkins  31.0
293          Quincy Pondexter  28.0
294         LaMarcus Aldridge  30.0
295             Kyle Anderson  22.0
296               Matt Bonner  36.0
297                Boris Diaw  34.0
298                Tim Duncan  40.0
299             Manu Ginobili  38.0
300               Danny Green  28.0
301             Kawhi Leonard  24.0
302          Boban Marjanovic  27.0
303              Kevin Martin  33.0
304              Andre Miller  40.0
305               Patty Mills  27.0
306               Tony Parker  34.0
307          Jonathon Simmons  26.0
308                David West  35.0
309             Kent Bazemore  26.0
310          Tim Hardaway Jr.  24.0
311              Kirk Hinrich  35.0
312                Al Horford  30.0
313            Kris Humphries  31.0
314               Kyle Korver  35.0
315              Paul Millsap  31.0
316              Mike Muscala  24.0
317           Lamar Patterson  24.0
318           Dennis Schroder  22.0
319                Mike Scott  27.0
320           Thabo Sefolosha  32.0
321            Tiago Splitter  31.0
322            Walter Tavares  24.0
323               Jeff Teague  27.0
324             Nicolas Batum  27.0
325              Troy Daniels  24.0
326           Jorge Gutierrez  27.0
327          Tyler Hansbrough  30.0
328            Aaron Harrison  21.0
329             Spencer Hawes  28.0
330              Al Jefferson  31.0
331        Frank Kaminsky III  23.0
332    Michael Kidd-Gilchrist  22.0
333               Jeremy Lamb  24.0
334              Courtney Lee  30.0
335                Jeremy Lin  27.0
336              Kemba Walker  26.0
337           Marvin Williams  29.0
338               Cody Zeller  23.0
339                Chris Bosh  32.0
340                 Luol Deng  31.0
341              Goran Dragic  30.0
342              Gerald Green  30.0
343             Udonis Haslem  36.0
344               Joe Johnson  34.0
345             Tyler Johnson  24.0
346            Josh McRoberts  29.0
347           Josh Richardson  22.0
348         Amar'e Stoudemire  33.0
349               Dwyane Wade  34.0
350             Briante Weber  23.0
351          Hassan Whiteside  26.0
352           Justise Winslow  20.0
353             Dorell Wright  30.0
354            Dewayne Dedmon  26.0
355             Evan Fournier  23.0
356              Aaron Gordon  20.0
357             Mario Hezonja  21.0
358            Ersan Ilyasova  29.0
359          Brandon Jennings  26.0
360              Devyn Marble  23.0
361            Shabazz Napier  24.0
362          Andrew Nicholson  26.0
363            Victor Oladipo  24.0
364             Elfrid Payton  22.0
365               Jason Smith  30.0
366            Nikola Vucevic  25.0
367               C.J. Watson  32.0
368             Alan Anderson  33.0
369              Bradley Beal  22.0
370              Jared Dudley  30.0
371              Jarell Eddie  24.0
372               Drew Gooden  34.0
373             Marcin Gortat  32.0
374                JJ Hickson  27.0
375              Nene Hilario  33.0
376           Markieff Morris  26.0
377           Kelly Oubre Jr.  20.0
378           Otto Porter Jr.  23.0
379            Ramon Sessions  30.0
380            Garrett Temple  30.0
381           Marcus Thornton  29.0
382                 John Wall  25.0
383            Darrell Arthur  28.0
384             D.J. Augustin  28.0
385               Will Barton  25.0
386           Wilson Chandler  29.0
387            Kenneth Faried  26.0
388          Danilo Gallinari  27.0
389               Gary Harris  21.0
390              Nikola Jokic  21.0
391         Joffrey Lauvergne  24.0
392               Mike Miller  36.0
393           Emmanuel Mudiay  20.0
394             Jameer Nelson  34.0
395              Jusuf Nurkic  21.0
396            JaKarr Sampson  23.0
397              Axel Toupane  23.0
398           Nemanja Bjelica  28.0
399              Gorgui Dieng  26.0
400             Kevin Garnett  40.0
401                Tyus Jones  20.0
402               Zach LaVine  21.0
403          Shabazz Muhammad  23.0
404             Adreian Payne  25.0
405            Nikola Pekovic  30.0
406           Tayshaun Prince  36.0
407               Ricky Rubio  25.0
408              Damjan Rudez  29.0
409                Greg Smith  25.0
410        Karl-Anthony Towns  20.0
411            Andrew Wiggins  21.0
412              Steven Adams  22.0
413             Nick Collison  35.0
414              Kevin Durant  27.0
415                Randy Foye  32.0
416              Josh Huestis  24.0
417               Serge Ibaka  26.0
418               Enes Kanter  24.0
419              Mitch McGary  24.0
420             Nazr Mohammed  38.0
421            Anthony Morrow  30.0
422             Cameron Payne  21.0
423            Andre Roberson  24.0
424              Kyle Singler  28.0
425              Dion Waiters  24.0
426         Russell Westbrook  27.0
427           Cliff Alexander  20.0
428           Al-Farouq Aminu  25.0
429           Pat Connaughton  23.0
430              Allen Crabbe  24.0
431                  Ed Davis  27.0
432          Maurice Harkless  23.0
433          Gerald Henderson  28.0
434               Chris Kaman  34.0
435            Meyers Leonard  24.0
436            Damian Lillard  25.0
437             C.J. McCollum  24.0
438              Luis Montero  23.0
439             Mason Plumlee  26.0
440             Brian Roberts  30.0
441               Noah Vonleh  20.0
442             Trevor Booker  28.0
443                Trey Burke  23.0
444                Alec Burks  24.0
445                Dante Exum  20.0
446            Derrick Favors  24.0
447               Rudy Gobert  23.0
448            Gordon Hayward  26.0
449               Rodney Hood  23.0
450                Joe Ingles  28.0
451             Chris Johnson  26.0
452                       NaN   NaN
453              Shelvin Mack  26.0
454                 Raul Neto  24.0
455              Tibor Pleiss  26.0
456               Jeff Withey  26.0

In [40]:
df = pd.read_csv('nba.csv')

# INTENDATION

In [46]:
df.isnull().sum()

Name        0
Team        0
Number      0
Position    0
Age         0
Height      0
Weight      0
College     0
Salary      0
Bonus       0
Sales       0
dtype: int64

In [45]:
df = df.fillna(0)

In [47]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 457 entries, 0 to 456
Data columns (total 11 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Name      457 non-null    object
 1   Team      457 non-null    object
 2   Number    457 non-null    float64
 3   Position  457 non-null    object
 4   Age       457 non-null    float64
 5   Height    457 non-null    object
 6   Weight    457 non-null    float64
 7   College   457 non-null    object
 8   Salary    457 non-null    float64
 9   Bonus     457 non-null    float64
 10  Sales     457 non-null    float64
dtypes: float64(6), object(5)
memory usage: 39.4+ KB

In [48]:
df = pd.read_csv('nba.csv')

In [53]:
df.isnull().sum()

Name          1
Team          1
Number        1
Position      1
Age           0
Height        1
Weight        1
College      85
Salary       12
Bonus       457
Sales       457
dtype: int64

In [52]:
df['Age'] = df['Age'].fillna(0)

In [56]:
df.isnull().sum()

Name          0
Team          1
Number        1
Position      1
Age           0
Height        1
Weight        1
College      85
Salary       12
Bonus       457
Sales       457
dtype: int64

In [55]:
df['Name'] = df['Name'].fillna("No Name")

In [62]:
df['Salary'] = df['Salary'].fillna(0)

In [63]:
df.isnull().sum()

Name          0
Team          1
Number        1
Position      1
Age           0
Height        1
Weight        1
College      85
Salary        0
Bonus       457
Sales       457
dtype: int64

In [65]:
df['Salary'] = df['Salary'].astype(int)

In [66]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 457 entries, 0 to 456
Data columns (total 11 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Name      457 non-null    object
 1   Team      456 non-null    object
 2   Number    456 non-null    float64
 3   Position  456 non-null    object
 4   Age       457 non-null    float64
 5   Height    456 non-null    object
 6   Weight    456 non-null    float64
 7   College   372 non-null    object
 8   Salary    457 non-null    int32
 9   Bonus     0 non-null      float64
 10  Sales     0 non-null      float64
dtypes: float64(5), int32(1), object(5)
memory usage: 37.6+ KB

In [67]:
df.head(3)

,Name,Team,Number,Position,Age,Height,Weight,College,Salary,Bonus,Sales
0,Avery Bradley,Boston Celtics,0.0,PG,25.0,06-Feb,180.0,Texas,7730337,NaN,NaN
1,Jae Crowder,Boston Celtics,99.0,SF,25.0,06-Jun,235.0,Marquette,6796117,NaN,NaN
2,John Holland,Boston Celtics,30.0,SG,27.0,06-May,205.0,Boston University,0,NaN,NaN

In [72]:
df.drop(columns=['Name','Team'])

,Number,Position,Age,Height,Weight,College,Salary,Bonus,Sales
0,0.0,PG,25.0,06-Feb,180.0,Texas,7730337,NaN,NaN
1,99.0,SF,25.0,06-Jun,235.0,Marquette,6796117,NaN,NaN
2,30.0,SG,27.0,06-May,205.0,Boston University,0,NaN,NaN
3,28.0,SG,22.0,06-May,185.0,Georgia State,1148640,NaN,NaN
4,8.0,PF,29.0,06-Oct,231.0,NaN,5000000,NaN,NaN
5,90.0,PF,29.0,06-Sep,240.0,NaN,12000000,NaN,NaN
6,55.0,PF,21.0,06-Aug,235.0,LSU,1170960,NaN,NaN
7,41.0,C,25.0,7-0,238.0,Gonzaga,2165160,NaN,NaN
8,12.0,PG,22.0,06-Feb,190.0,Louisville,1824360,NaN,NaN
9,36.0,PG,22.0,06-Apr,220.0,Oklahoma State,3431040,NaN,NaN
10,7.0,C,24.0,06-Sep,260.0,Ohio State,2569260,NaN,NaN
11,4.0,PG,27.0,05-Sep,185.0,Washington,6912869,NaN,NaN
12,11.0,SG,27.0,06-Jul,220.0,Ohio State,3425510,NaN,NaN
13,13.0,SG,20.0,06-Jun,215.0,Kentucky,1749840,NaN,NaN
14,44.0,C,26.0,7-0,253.0,North Carolina,2616975,NaN,NaN
15,44.0,SG,27.0,06-Aug,216.0,NaN,3425510,NaN,NaN
16,22.0,SG,24.0,06-Mar,190.0,Oklahoma State,845059,NaN,NaN
17,21.0,SG,28.0,06-Apr,200.0,North Carolina,1500000,NaN,NaN
18,24.0,SG,21.0,06-Jul,220.0,Arizona,1335480,NaN,NaN
19,2.0,PG,32.0,06-Mar,200.0,Georgia Tech,6300000,NaN,NaN
20,10.0,SG,22.0,06-Jul,208.0,NaN,1599840,NaN,NaN
21,6.0,SG,26.0,06-Apr,219.0,Cincinnati,134215,NaN,NaN
22,0.0,PG,23.0,05-Nov,175.0,Miami (FL),1500000,NaN,NaN
23,11.0,C,28.0,7-0,275.0,Stanford,19689000,NaN,NaN
24,1.0,PF,21.0,06-Nov,200.0,Syracuse,1140240,NaN,NaN
25,33.0,PF,26.0,06-Oct,220.0,Saint Louis,947276,NaN,NaN
26,41.0,PF,25.0,06-Oct,237.0,Kansas,981348,NaN,NaN
27,14.0,C,26.0,06-Oct,248.0,Georgetown,947276,NaN,NaN
28,15.0,PG,28.0,06-Mar,205.0,Texas A&M,947276,NaN,NaN
29,30.0,PF,27.0,06-Aug,221.0,Georgia Tech,11235955,NaN,NaN
30,4.0,SG,30.0,06-May,210.0,UCLA,8000000,NaN,NaN
31,17.0,PF,33.0,06-Sep,220.0,UNLV,1635476,NaN,NaN
32,43.0,SF,23.0,06-Jul,205.0,NaN,30888,NaN,NaN
33,7.0,SF,32.0,06-Aug,240.0,Syracuse,22875000,NaN,NaN
34,3.0,PG,34.0,06-Mar,200.0,NaN,7402812,NaN,NaN
35,11.0,SF,25.0,06-Aug,210.0,Wichita State,845059,NaN,NaN
36,2.0,SG,24.0,06-Feb,200.0,Saint Joseph's,845059,NaN,NaN
37,13.0,PG,23.0,06-Apr,195.0,Notre Dame,1572360,NaN,NaN
38,8.0,C,28.0,7-0,255.0,Stanford,12650000,NaN,NaN
39,9.0,PF,26.0,06-Oct,250.0,Norfolk State,3750000,NaN,NaN
40,6.0,PF,20.0,07-Mar,240.0,NaN,4131720,NaN,NaN
41,1.0,C,26.0,06-Oct,278.0,NaN,2814000,NaN,NaN
42,42.0,SF,28.0,06-Aug,235.0,Duke,1636842,NaN,NaN
43,18.0,SG,32.0,06-Jul,195.0,NaN,947276,NaN,NaN
44,23.0,PF,25.0,06-Aug,240.0,Arizona,4000000,NaN,NaN
45,5.0,SG,23.0,06-Jun,205.0,Washington,167406,NaN,NaN
46,42.0,PF,37.0,06-Sep,254.0,Duke,0,NaN,NaN
47,0.0,PG,25.0,6-0,201.0,Murray State,947276,NaN,NaN
48,33.0,SF,25.0,06-Sep,215.0,Tennessee State,1000000,NaN,NaN
49,21.0,C,22.0,7-0,250.0,Kansas,4626960,NaN,NaN
50,39.0,SF,22.0,06-Aug,210.0,Syracuse,845059,NaN,NaN
51,22.0,PF,22.0,06-Oct,245.0,Bowling Green,1074169,NaN,NaN
52,7.0,PF,32.0,06-Sep,248.0,Purdue,6500000,NaN,NaN
53,5.0,PG,24.0,06-Apr,200.0,North Carolina,2144772,NaN,NaN
54,12.0,PG,24.0,06-Feb,200.0,Arizona,525093,NaN,NaN
55,4.0,PF,22.0,06-Nov,228.0,Kentucky,3457800,NaN,NaN
56,8.0,C,20.0,06-Nov,275.0,Duke,4582680,NaN,NaN
57,1.0,PG,27.0,6-0,175.0,Wake Forest,947276,NaN,NaN
58,11.0,SG,22.0,06-Jun,205.0,Michigan,2869440,NaN,NaN
59,31.0,SG,25.0,06-Aug,206.0,Georgetown,947276,NaN,NaN
60,35.0,PF,20.0,06-Nov,220.0,UNLV,525093,NaN,NaN
61,8.0,C,23.0,06-Sep,245.0,NaN,2814000,NaN,NaN
62,20.0,SF,20.0,06-Sep,205.0,NaN,1524000,NaN,NaN
63,5.0,SF,29.0,06-Aug,212.0,Missouri,13600000,NaN,NaN
64,10.0,SG,26.0,06-Jul,220.0,USC,10050000,NaN,NaN
65,3.0,PF,29.0,06-Sep,250.0,Wake Forest,2500000,NaN,NaN
66,6.0,PG,24.0,06-Mar,190.0,Texas,7000000,NaN,NaN
67,7.0,PG,30.0,6-0,205.0,Villanova,12000000,NaN,NaN
68,92.0,C,23.0,7-0,220.0,NaN,1842000,NaN,NaN
69,54.0,PF,27.0,06-Sep,235.0,Kentucky,6268675,NaN,NaN
70,24.0,SG,23.0,06-Apr,215.0,UCLA,650000,NaN,NaN
71,31.0,SF,25.0,06-Jul,195.0,Washington,3553917,NaN,NaN
72,4.0,PF,36.0,06-Sep,240.0,NaN,2900000,NaN,NaN
73,1.0,PF,29.0,06-Nov,250.0,Rider,245177,NaN,NaN
74,17.0,C,24.0,7-0,255.0,NaN,4660482,NaN,NaN
75,55.0,PG,24.0,06-May,190.0,Utah,1509360,NaN,NaN
76,19.0,SG,33.0,06-Mar,194.0,NaN,2500000,NaN,NaN
77,40.0,SF,24.0,06-Aug,225.0,North Carolina,3873398,NaN,NaN
78,12.0,C,31.0,7-0,260.0,Utah,13800000,NaN,NaN
79,21.0,SG,25.0,06-Mar,175.0,Belmont,947276,NaN,NaN
80,30.0,PG,28.0,06-Mar,190.0,Davidson,11370786,NaN,NaN
81,31.0,C,26.0,06-Nov,265.0,Vanderbilt,2008748,NaN,NaN
82,23.0,PF,26.0,06-Jul,230.0,Michigan State,14260870,NaN,NaN
83,9.0,SF,32.0,06-Jun,215.0,Arizona,11710456,NaN,NaN
84,34.0,PG,30.0,06-Jul,192.0,NaN,5543725,NaN,NaN
85,36.0,SF,20.0,06-Sep,220.0,UCLA,1131960,NaN,NaN
86,20.0,SF,23.0,06-Sep,240.0,North Carolina,845059,NaN,NaN
87,4.0,SF,30.0,06-Jun,220.0,Kansas,1270964,NaN,NaN
88,5.0,C,28.0,06-Oct,255.0,Florida,3815000,NaN,NaN
89,11.0,SG,26.0,06-Jul,215.0,Washington State,15501000,NaN,NaN
90,18.0,PF,33.0,06-Nov,273.0,NaN,289755,NaN,NaN
91,45.0,C,27.0,06-Nov,250.0,Kansas,1100602,NaN,NaN
92,19.0,PF,29.0,06-Sep,250.0,Arizona State,111444,NaN,NaN
93,11.0,SG,36.0,06-May,195.0,Michigan,5675000,NaN,NaN
94,22.0,SF,23.0,06-Jun,225.0,Michigan State,525093,NaN,NaN
95,8.0,SF,29.0,06-Sep,235.0,Georgetown,9650000,NaN,NaN
96,32.0,PF,27.0,06-Oct,251.0,Oklahoma,18907726,NaN,NaN
97,33.0,SF,28.0,06-Jul,215.0,Syracuse,1100602,NaN,NaN
98,6.0,C,27.0,06-Nov,265.0,Texas A&M,19689000,NaN,NaN
99,12.0,PF,29.0,06-Aug,230.0,UCLA,947276,NaN,NaN
100,3.0,PG,31.0,6-0,175.0,Wake Forest,21468695,NaN,NaN
101,34.0,SF,38.0,06-Jul,235.0,Kansas,3376000,NaN,NaN
102,9.0,PG,39.0,06-Mar,185.0,NaN,947726,NaN,NaN
103,4.0,SG,31.0,06-Apr,190.0,Duke,7085000,NaN,NaN
104,25.0,PG,23.0,06-Apr,200.0,Duke,3110796,NaN,NaN
105,30.0,SG,25.0,06-May,195.0,Washington,1159680,NaN,NaN
106,2.0,PF,31.0,06-Aug,250.0,LSU,3000000,NaN,NaN
107,28.0,C,24.0,06-Sep,250.0,Kansas,845059,NaN,NaN
108,3.0,SF,23.0,06-Jul,210.0,Stanford,700000,NaN,NaN
109,24.0,SF,37.0,06-Jun,212.0,NaN,25000000,NaN,NaN
110,6.0,PG,24.0,06-May,194.0,Missouri,845059,NaN,NaN
111,17.0,C,29.0,07-Feb,270.0,Georgetown,15592217,NaN,NaN
112,9.0,PG,33.0,06-Mar,200.0,NaN,525093,NaN,NaN
113,4.0,PF,25.0,06-Nov,230.0,Duke,1724250,NaN,NaN
114,7.0,PF,23.0,06-Sep,230.0,Wyoming,1155600,NaN,NaN
115,30.0,PF,21.0,06-Sep,250.0,Kentucky,3132240,NaN,NaN
116,1.0,PG,20.0,06-May,195.0,Ohio State,5103120,NaN,NaN
117,50.0,C,27.0,7-0,270.0,Gonzaga,981348,NaN,NaN
118,23.0,SG,29.0,06-Jan,175.0,NaN,7000000,NaN,NaN
119,37.0,SF,36.0,06-Jul,260.0,St. John's,947276,NaN,NaN
120,0.0,SF,31.0,06-Jul,210.0,USC,5219169,NaN,NaN
121,2.0,PG,26.0,06-Jan,190.0,Kentucky,13500000,NaN,NaN
122,1.0,SG,19.0,06-Jun,206.0,Kentucky,2127840,NaN,NaN
123,10.0,SF,28.0,06-Jul,209.0,Arizona,206192,NaN,NaN
124,4.0,C,33.0,07-Jan,240.0,NaN,13000000,NaN,NaN
125,20.0,SG,21.0,06-May,200.0,Kentucky,1160160,NaN,NaN
126,23.0,SG,25.0,06-Apr,215.0,Vanderbilt,981348,NaN,NaN
127,3.0,PG,24.0,06-Mar,189.0,Kentucky,13500000,NaN,NaN
128,21.0,C,22.0,07-Jan,260.0,Maryland,3807120,NaN,NaN
129,30.0,PF,27.0,06-Oct,228.0,Wisconsin,1035000,NaN,NaN
130,25.0,PG,25.0,05-Nov,175.0,Missouri,55722,NaN,NaN
131,14.0,PG,32.0,06-Feb,190.0,Utah Valley,947276,NaN,NaN
132,35.0,PF,30.0,06-Sep,242.0,NaN,5500000,NaN,NaN
133,17.0,SF,31.0,06-Jun,245.0,Texas,5500000,NaN,NaN
134,12.0,SF,22.0,06-Aug,230.0,North Carolina State,2041080,NaN,NaN
135,15.0,C,23.0,06-Aug,260.0,UC Santa Barbara,83397,NaN,NaN
136,13.0,SF,25.0,06-Jul,240.0,Baylor,981348,NaN,NaN
137,5.0,SG,27.0,06-Jun,213.0,Oklahoma State,1015421,NaN,NaN
138,3.0,SG,30.0,06-May,210.0,NaN,6060606,NaN,NaN
139,31.0,SF,36.0,06-Jul,228.0,Connecticut,1449187,NaN,NaN
140,18.0,SF,27.0,06-Sep,225.0,NaN,2836186,NaN,NaN
141,0.0,C,22.0,7-0,240.0,Kentucky,3398280,NaN,NaN
142,7.0,PG,28.0,6-0,175.0,UCLA,5013559,NaN,NaN
143,15.0,C,25.0,06-Nov,270.0,Kentucky,15851950,NaN,NaN
144,30.0,SG,25.0,06-Feb,185.0,Duke,947276,NaN,NaN
145,26.0,PF,24.0,06-Sep,220.0,Wisconsin,525093,NaN,NaN
146,8.0,SF,29.0,06-Aug,230.0,Connecticut,12403101,NaN,NaN
147,41.0,C,27.0,7-0,265.0,Ohio State,7700000,NaN,NaN
148,23.0,SG,23.0,06-May,195.0,Kansas,3156600,NaN,NaN
149,25.0,PF,24.0,06-Oct,238.0,Oregon State,845059,NaN,NaN
150,9.0,PG,30.0,06-Jan,186.0,Kentucky,9500000,NaN,NaN
151,41.0,PF,25.0,06-Sep,250.0,New Mexico,845059,NaN,NaN
152,0.0,PG,31.0,6-0,161.0,Oregon,2250000,NaN,NaN
153,21.0,SG,26.0,06-Jul,220.0,Marquette,16407500,NaN,NaN
154,34.0,SG,35.0,06-Sep,230.0,Duke,4500000,NaN,NaN
155,6.0,PF,23.0,06-Oct,275.0,NaN,525093,NaN,NaN
156,16.0,C,35.0,7-0,250.0,NaN,7448760,NaN,NaN
157,22.0,PF,30.0,06-Sep,225.0,USC,8500000,NaN,NaN
158,7.0,SG,27.0,06-Jun,185.0,Washington,947276,NaN,NaN
159,3.0,SF,24.0,06-Aug,225.0,Creighton,2380440,NaN,NaN
160,44.0,PF,25.0,06-Oct,220.0,NaN,5543725,NaN,NaN
161,55.0,SG,27.0,06-Apr,191.0,Purdue,1015421,NaN,NaN
162,13.0,C,31.0,06-Nov,232.0,Florida,13400000,NaN,NaN
163,5.0,PF,21.0,06-Nov,230.0,Arkansas,1391160,NaN,NaN
164,1.0,PG,27.0,06-Mar,190.0,Memphis,20093064,NaN,NaN
165,20.0,SF,24.0,06-Jul,200.0,New Mexico,1535880,NaN,NaN
166,8.0,PG,25.0,06-Apr,198.0,Saint Mary's,1147276,NaN,NaN
167,9.0,PF,33.0,06-Nov,255.0,Arizona,8193029,NaN,NaN
168,2.0,PG,24.0,06-Mar,193.0,Duke,16407501,NaN,NaN
169,23.0,SF,31.0,06-Aug,250.0,NaN,22970500,NaN,NaN
170,24.0,SF,35.0,06-Jul,233.0,Arizona,947276,NaN,NaN
171,30.0,SG,35.0,06-Jun,225.0,Duke,0,NaN,NaN
172,1.0,SG,35.0,06-Aug,218.0,Miami (FL),947276,NaN,NaN
173,14.0,C,31.0,06-Nov,260.0,Kansas,1276000,NaN,NaN
174,0.0,PF,27.0,06-Oct,251.0,UCLA,19689000,NaN,NaN
175,12.0,SG,25.0,06-May,179.0,Tennessee,111196,NaN,NaN
176,20.0,C,29.0,07-Jan,275.0,NaN,4950000,NaN,NaN
177,4.0,SG,25.0,06-May,220.0,Georgia Tech,8988765,NaN,NaN
178,5.0,SG,30.0,06-Jun,225.0,NaN,5000000,NaN,NaN
179,13.0,C,25.0,06-Sep,238.0,Texas,14260870,NaN,NaN
180,52.0,PG,33.0,06-Jan,198.0,Alabama,2100000,NaN,NaN
181,50.0,C,33.0,06-Sep,245.0,UNLV,2500000,NaN,NaN
182,12.0,C,29.0,06-Oct,260.0,Washington State,6500000,NaN,NaN
183,22.0,PG,36.0,06-Mar,172.0,Maryland,2170465,NaN,NaN
184,17.0,PG,25.0,06-May,189.0,North Carolina State,111444,NaN,NaN
185,25.0,SF,25.0,06-Jul,205.0,North Carolina,1252440,NaN,NaN
186,5.0,SG,23.0,06-May,205.0,Georgia,2891760,NaN,NaN
187,8.0,PG,23.0,06-Jun,200.0,Colorado,845059,NaN,NaN
188,0.0,C,22.0,06-Nov,279.0,Connecticut,3272091,NaN,NaN
189,34.0,SF,23.0,06-Sep,235.0,Tennessee,16000000,NaN,NaN
190,6.0,SF,23.0,06-Jun,205.0,Villanova,600000,NaN,NaN
191,1.0,PG,26.0,06-Mar,208.0,Boston College,13913044,NaN,NaN
192,3.0,SF,20.0,06-Jul,245.0,Arizona,2841960,NaN,NaN
193,20.0,SG,28.0,06-Apr,210.0,Kentucky,6270000,NaN,NaN
194,13.0,PF,26.0,06-Sep,235.0,Kansas,5000000,NaN,NaN
195,43.0,PF,31.0,06-Aug,240.0,Creighton,3000000,NaN,NaN
196,5.0,PF,27.0,06-Sep,255.0,Temple,4050000,NaN,NaN
197,25.0,PF,24.0,06-Sep,250.0,Syracuse,1007026,NaN,NaN
198,11.0,SG,30.0,06-Mar,185.0,NaN,10300000,NaN,NaN
199,13.0,SF,26.0,06-Sep,220.0,Fresno State,17120106,NaN,NaN
200,3.0,PG,30.0,06-Mar,188.0,IUPUI,8000000,NaN,NaN
201,27.0,C,28.0,06-Oct,235.0,Arizona,4000000,NaN,NaN
202,44.0,SF,25.0,06-Jul,225.0,Arizona,1358880,NaN,NaN
203,10.0,PG,28.0,05-Nov,195.0,North Carolina,211744,NaN,NaN
204,28.0,C,29.0,06-Nov,250.0,NaN,4000000,NaN,NaN
205,0.0,SF,29.0,06-Jun,231.0,NaN,4394225,NaN,NaN
206,40.0,SG,22.0,06-Jul,222.0,Michigan,1100000,NaN,NaN
207,2.0,PG,30.0,06-May,205.0,Eastern Washington,7000000,NaN,NaN
208,33.0,PF,20.0,06-Nov,243.0,Texas,2357760,NaN,NaN
209,42.0,PF,25.0,06-Nov,250.0,Western Michigan,845059,NaN,NaN
210,1.0,PG,23.0,06-Feb,180.0,Oregon,1007026,NaN,NaN
211,34.0,SF,21.0,06-Nov,222.0,NaN,1953960,NaN,NaN
212,19.0,PG,27.0,06-Mar,200.0,Arizona,3000000,NaN,NaN
213,5.0,PG,24.0,06-Jun,190.0,Syracuse,2399040,NaN,NaN
214,9.0,SG,25.0,06-Apr,195.0,Oregon State,947276,NaN,NaN
215,11.0,PG,21.0,06-Mar,194.0,Syracuse,1662360,NaN,NaN
216,31.0,PF,25.0,06-Nov,229.0,North Carolina,2943221,NaN,NaN
217,17.0,SF,21.0,06-Aug,246.0,NaN,855000,NaN,NaN
218,3.0,SG,28.0,06-May,210.0,USC,8000000,NaN,NaN
219,22.0,SG,24.0,06-Aug,234.0,Texas A&M,14700000,NaN,NaN
220,15.0,C,26.0,06-Nov,265.0,Georgetown,16407500,NaN,NaN
221,6.0,SF,32.0,06-Oct,225.0,Marquette,295327,NaN,NaN
222,77.0,PF,23.0,06-Sep,257.0,LSU,845059,NaN,NaN
223,12.0,PF,21.0,06-Aug,250.0,Duke,5152440,NaN,NaN
224,18.0,C,27.0,06-Nov,249.0,Duke,2109294,NaN,NaN
225,21.0,PG,29.0,06-Jun,217.0,Maryland,6600000,NaN,NaN
226,20.0,SG,19.0,06-Jun,202.0,UNLV,1733040,NaN,NaN
227,1.0,SG,22.0,06-Jun,228.0,Virginia,1449000,NaN,NaN
228,5.0,PG,31.0,6-0,185.0,Northeastern,4290000,NaN,NaN
229,21.0,SF,28.0,06-Sep,200.0,Western Kentucky,1100602,NaN,NaN
230,2.0,PG,31.0,06-Jan,205.0,North Carolina,3950313,NaN,NaN
231,34.0,PG,33.0,06-Mar,185.0,Wisconsin,4053446,NaN,NaN
232,42.0,PF,33.0,06-Sep,245.0,Florida,2085671,NaN,NaN
233,23.0,SG,29.0,06-May,220.0,Marquette,16407500,NaN,NaN
234,11.0,C,28.0,7-0,270.0,Nevada,1270964,NaN,NaN
235,50.0,C,29.0,07-Feb,245.0,NaN,525093,NaN,NaN
236,41.0,PF,37.0,7-0,245.0,NaN,8333334,NaN,NaN
237,27.0,C,32.0,06-Nov,275.0,NaN,5200000,NaN,NaN
238,25.0,SF,27.0,06-Oct,230.0,Florida,15361500,NaN,NaN
239,7.0,PF,24.0,06-Nov,240.0,Stanford,845059,NaN,NaN
240,3.0,PF,31.0,06-Nov,232.0,Connecticut,947276,NaN,NaN
241,8.0,PG,31.0,06-Mar,200.0,Illinois,5378974,NaN,NaN
242,1.0,SF,30.0,06-Aug,215.0,UCLA,8193030,NaN,NaN
243,8.0,SF,27.0,06-Oct,235.0,Kansas State,306527,NaN,NaN
244,2.0,PG,27.0,06-Jan,185.0,Arkansas,6486486,NaN,NaN
245,33.0,SG,30.0,06-Sep,186.0,Florida,8229375,NaN,NaN
246,15.0,PF,22.0,06-Oct,240.0,NaN,1242720,NaN,NaN
247,7.0,SF,22.0,06-Sep,230.0,Wisconsin,1646400,NaN,NaN
248,0.0,PG,27.0,06-Mar,200.0,Charleston,200600,NaN,NaN
249,13.0,SG,26.0,06-May,220.0,Arizona State,15756438,NaN,NaN
250,35.0,PF,22.0,06-Aug,240.0,Louisville,1000000,NaN,NaN
251,12.0,C,30.0,06-Nov,265.0,NaN,22359364,NaN,NaN
252,6.0,PF,24.0,06-Sep,252.0,Kentucky,2489530,NaN,NaN
253,32.0,SG,23.0,06-Jun,205.0,Clemson,3189794,NaN,NaN
254,20.0,PF,25.0,7-0,222.0,NaN,2288205,NaN,NaN
255,5.0,C,30.0,06-Sep,225.0,NaN,947276,NaN,NaN
256,31.0,SG,38.0,06-Feb,185.0,Arizona,947276,NaN,NaN
257,3.0,SG,21.0,06-May,209.0,UCLA,1404600,NaN,NaN
258,9.0,SG,34.0,06-Apr,213.0,Oklahoma State,5158539,NaN,NaN
259,7.0,PF,37.0,06-Oct,245.0,Blinn College,5000000,NaN,NaN
260,22.0,SF,36.0,06-Jul,226.0,UCLA,3542500,NaN,NaN
261,15.0,SG,39.0,06-Jun,220.0,North Carolina,4088019,NaN,NaN
262,11.0,PG,28.0,06-Jan,175.0,Ohio State,9588426,NaN,NaN
263,8.0,PG,23.0,06-Jan,165.0,Providence,700902,NaN,NaN
264,4.0,PG,29.0,06-Feb,180.0,UCLA,0,NaN,NaN
265,33.0,C,31.0,07-Jan,255.0,NaN,19688000,NaN,NaN
266,0.0,PF,25.0,06-Sep,227.0,Alabama,845059,NaN,NaN
267,19.0,SF,23.0,06-Jun,230.0,North Carolina,1201440,NaN,NaN
268,10.0,PF,22.0,06-Oct,239.0,LSU,1230840,NaN,NaN
269,5.0,PG,24.0,06-Mar,190.0,Detroit,0,NaN,NaN
270,14.0,PG,24.0,06-Mar,180.0,Rhode Island,0,NaN,NaN
271,50.0,PF,34.0,06-Sep,260.0,Michigan State,9638555,NaN,NaN
272,1.0,SF,25.0,06-May,230.0,Cincinnati,9000000,NaN,NaN
273,35.0,PF,28.0,06-Oct,270.0,USC,0,NaN,NaN
274,34.0,PF,28.0,06-Oct,210.0,North Carolina,5464000,NaN,NaN
275,42.0,C,28.0,07-Feb,248.0,NaN,4389607,NaN,NaN
276,33.0,PF,28.0,06-Oct,240.0,California,8500000,NaN,NaN
277,3.0,C,29.0,7-0,255.0,NaN,9213483,NaN,NaN
278,8.0,SF,26.0,06-Sep,225.0,Nevada,1100602,NaN,NaN
279,30.0,PG,27.0,06-Feb,175.0,Cleveland State,3036927,NaN,NaN
280,44.0,PF,29.0,06-Aug,230.0,Villanova,2850000,NaN,NaN
281,23.0,PF,23.0,06-Oct,253.0,Kentucky,7070730,NaN,NaN
282,31.0,SG,23.0,06-Jun,203.0,Iowa State,169883,NaN,NaN
283,16.0,PG,30.0,06-Feb,195.0,Florida State,1164858,NaN,NaN
284,4.0,SF,25.0,06-Jul,210.0,Long Beach State,845059,NaN,NaN
285,1.0,SG,26.0,06-Jun,220.0,Memphis,10734586,NaN,NaN
286,2.0,PG,25.0,06-Jan,170.0,Penn State,845059,NaN,NaN
287,15.0,SF,29.0,06-Jun,225.0,Alabama,1320000,NaN,NaN
288,10.0,SG,27.0,06-Apr,215.0,Indiana,15514031,NaN,NaN
289,25.0,SG,25.0,06-Jul,220.0,Texas,1015421,NaN,NaN
290,11.0,PG,25.0,06-Apr,205.0,UCLA,10595507,NaN,NaN
291,0.0,SG,27.0,06-May,220.0,UC Santa Barbara,55722,NaN,NaN
292,5.0,C,31.0,06-Oct,270.0,NaN,947276,NaN,NaN
293,20.0,SF,28.0,06-Jul,220.0,Washington,3382023,NaN,NaN
294,12.0,PF,30.0,06-Nov,240.0,Texas,19689000,NaN,NaN
295,1.0,SF,22.0,06-Sep,230.0,UCLA,1142880,NaN,NaN
296,15.0,C,36.0,06-Oct,235.0,Florida,947276,NaN,NaN
297,33.0,C,34.0,06-Aug,250.0,NaN,7500000,NaN,NaN
298,21.0,C,40.0,06-Nov,250.0,Wake Forest,5250000,NaN,NaN
299,20.0,SG,38.0,06-Jun,205.0,NaN,2814000,NaN,NaN
300,14.0,SG,28.0,06-Jun,215.0,North Carolina,10000000,NaN,NaN
301,2.0,SF,24.0,06-Jul,230.0,San Diego State,16407500,NaN,NaN
302,40.0,C,27.0,07-Mar,290.0,NaN,1200000,NaN,NaN
303,23.0,SG,33.0,06-Jul,199.0,Western Carolina,200600,NaN,NaN
304,24.0,PG,40.0,06-Mar,200.0,Utah,250750,NaN,NaN
305,8.0,PG,27.0,6-0,185.0,Saint Mary's,3578947,NaN,NaN
306,9.0,PG,34.0,06-Feb,185.0,NaN,13437500,NaN,NaN
307,17.0,SG,26.0,06-Jun,195.0,Houston,525093,NaN,NaN
308,30.0,PF,35.0,06-Sep,250.0,Xavier,1499187,NaN,NaN
309,24.0,SF,26.0,06-May,201.0,Old Dominion,2000000,NaN,NaN
310,10.0,SG,24.0,06-Jun,205.0,Michigan,1304520,NaN,NaN
311,12.0,SG,35.0,06-Apr,190.0,Kansas,2854940,NaN,NaN
312,15.0,C,30.0,06-Oct,245.0,Florida,12000000,NaN,NaN
313,43.0,PF,31.0,06-Sep,235.0,Minnesota,1000000,NaN,NaN
314,26.0,SG,35.0,06-Jul,212.0,Creighton,5746479,NaN,NaN
315,4.0,PF,31.0,06-Aug,246.0,Louisiana Tech,18671659,NaN,NaN
316,31.0,PF,24.0,06-Nov,240.0,Bucknell,947276,NaN,NaN
317,13.0,SG,24.0,06-May,225.0,Pittsburgh,525093,NaN,NaN
318,17.0,PG,22.0,06-Jan,172.0,NaN,1763400,NaN,NaN
319,32.0,PF,27.0,06-Aug,237.0,Virginia,3333333,NaN,NaN
320,25.0,SF,32.0,06-Jul,220.0,NaN,4000000,NaN,NaN
321,11.0,C,31.0,06-Nov,245.0,NaN,9756250,NaN,NaN
322,22.0,C,24.0,07-Mar,260.0,NaN,1000000,NaN,NaN
323,0.0,PG,27.0,06-Feb,186.0,Wake Forest,8000000,NaN,NaN
324,5.0,SG,27.0,06-Aug,200.0,NaN,13125306,NaN,NaN
325,30.0,SG,24.0,06-Apr,205.0,Virginia Commonwealth,947276,NaN,NaN
326,12.0,PG,27.0,06-Mar,189.0,California,189455,NaN,NaN
327,50.0,PF,30.0,06-Sep,250.0,North Carolina,947276,NaN,NaN
328,9.0,SG,21.0,06-Jun,210.0,Kentucky,525093,NaN,NaN
329,0.0,PF,28.0,07-Jan,245.0,Washington,6110034,NaN,NaN
330,25.0,C,31.0,06-Oct,289.0,NaN,13500000,NaN,NaN
331,44.0,C,23.0,7-0,240.0,Wisconsin,2612520,NaN,NaN
332,14.0,SF,22.0,06-Jul,232.0,Kentucky,6331404,NaN,NaN
333,3.0,SG,24.0,06-May,185.0,Connecticut,3034356,NaN,NaN
334,1.0,SG,30.0,06-May,200.0,Western Kentucky,5675000,NaN,NaN
335,7.0,PG,27.0,06-Mar,200.0,Harvard,2139000,NaN,NaN
336,15.0,PG,26.0,06-Jan,184.0,Connecticut,12000000,NaN,NaN
337,2.0,PF,29.0,06-Sep,237.0,North Carolina,7000000,NaN,NaN
338,40.0,C,23.0,7-0,240.0,Indiana,4204200,NaN,NaN
339,1.0,PF,32.0,06-Nov,235.0,Georgia Tech,22192730,NaN,NaN
340,9.0,SF,31.0,06-Sep,220.0,Duke,10151612,NaN,NaN
341,7.0,PG,30.0,06-Mar,190.0,NaN,14783000,NaN,NaN
342,14.0,SF,30.0,06-Jul,205.0,NaN,947276,NaN,NaN
343,40.0,PF,36.0,06-Aug,235.0,Florida,2854940,NaN,NaN
344,2.0,SF,34.0,06-Jul,240.0,Arkansas,261894,NaN,NaN
345,8.0,SG,24.0,06-Apr,186.0,Fresno State,845059,NaN,NaN
346,4.0,PF,29.0,06-Oct,240.0,Duke,5543725,NaN,NaN
347,0.0,SG,22.0,06-Jun,200.0,Tennessee,525093,NaN,NaN
348,5.0,PF,33.0,06-Oct,245.0,NaN,947276,NaN,NaN
349,3.0,SG,34.0,06-Apr,220.0,Marquette,20000000,NaN,NaN
350,12.0,PG,23.0,06-Feb,165.0,Virginia Commonwealth,0,NaN,NaN
351,21.0,C,26.0,7-0,265.0,Marshall,981348,NaN,NaN
352,20.0,SF,20.0,06-Jul,225.0,Duke,2481720,NaN,NaN
353,11.0,SF,30.0,06-Sep,205.0,NaN,0,NaN,NaN
354,3.0,C,26.0,7-0,245.0,USC,947276,NaN,NaN
355,10.0,SG,23.0,06-Jul,205.0,NaN,2288205,NaN,NaN
356,0.0,PF,20.0,06-Sep,220.0,Arizona,4171680,NaN,NaN
357,23.0,SG,21.0,06-Aug,218.0,NaN,3741480,NaN,NaN
358,7.0,PF,29.0,06-Oct,235.0,NaN,7900000,NaN,NaN
359,55.0,PG,26.0,06-Jan,169.0,NaN,8344497,NaN,NaN
360,11.0,SF,23.0,06-Jun,200.0,Iowa,845059,NaN,NaN
361,13.0,PG,24.0,06-Jan,175.0,Connecticut,1294440,NaN,NaN
362,44.0,PF,26.0,06-Sep,250.0,St. Bonaventure,2380593,NaN,NaN
363,5.0,SG,24.0,06-Apr,210.0,Indiana,5192520,NaN,NaN
364,4.0,PG,22.0,06-Apr,185.0,Louisiana-Lafayette,2505720,NaN,NaN
365,14.0,PF,30.0,7-0,240.0,Colorado State,4300000,NaN,NaN
366,9.0,C,25.0,7-0,260.0,USC,11250000,NaN,NaN
367,32.0,PG,32.0,06-Feb,175.0,Tennessee,5000000,NaN,NaN
368,6.0,SG,33.0,06-Jun,220.0,Michigan State,4000000,NaN,NaN
369,3.0,SG,22.0,06-May,207.0,Florida,5694674,NaN,NaN
370,1.0,SF,30.0,06-Jul,225.0,Boston College,4375000,NaN,NaN
371,8.0,SG,24.0,06-Jul,218.0,Virginia Tech,561716,NaN,NaN

In [71]:
df.head()

,Name,Team,Number,Position,Age,Height,Weight,College,Salary,Bonus,Sales
0,Avery Bradley,Boston Celtics,0.0,PG,25.0,06-Feb,180.0,Texas,7730337,NaN,NaN
1,Jae Crowder,Boston Celtics,99.0,SF,25.0,06-Jun,235.0,Marquette,6796117,NaN,NaN
2,John Holland,Boston Celtics,30.0,SG,27.0,06-May,205.0,Boston University,0,NaN,NaN
3,R.J. Hunter,Boston Celtics,28.0,SG,22.0,06-May,185.0,Georgia State,1148640,NaN,NaN
4,Jonas Jerebko,Boston Celtics,8.0,PF,29.0,06-Oct,231.0,NaN,5000000,NaN,NaN

# INSERT

In [75]:
df["Sports"] = "BasketBall"

In [76]:
df.head(3)

,Name,Team,Number,Position,Age,Height,Weight,College,Salary,Bonus,Sales,Sports
0,Avery Bradley,Boston Celtics,0.0,PG,25.0,06-Feb,180.0,Texas,7730337,NaN,NaN,BasketBall
1,Jae Crowder,Boston Celtics,99.0,SF,25.0,06-Jun,235.0,Marquette,6796117,NaN,NaN,BasketBall
2,John Holland,Boston Celtics,30.0,SG,27.0,06-May,205.0,Boston University,0,NaN,NaN,BasketBall